apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    name: backend
    release: prometheus
  annotations:
    sidecar.jaegertracing.io/inject: 'true'
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # We advise you to build, push and use your own image, instead of using instructor's image.      
        image: daoducnha29493/backend:v3
        env:
        - name: JAEGER_HOST
          value: simpletest-query.default.svc.cluster.local
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8081
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  namespace: monitoring
  labels:
    app: backend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: backend
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default