apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend    
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/path: /metrics
    prometheus.io/port: frontendport
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: daoducnha29493/frontend:v4
        env:
          - name: JAEGER_HOST
            value: simplest-query.observability.svc.cluster.local
        ports:
        - name: frontendport
          containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend
  namespace: monitoring
  labels:
    app: frontend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: frontend
  endpoints:
  - port: frontend
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default