apiVersion: apps/v1
kind: Deployment
metadata:
  name: trial
  labels:
    app: trial    
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
    # prometheus.io/scrape: "true"
    # prometheus.io/path: /metrics
    # prometheus.io/path: /metrics
    # prometheus.io/port: trailport
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trial
  template:
    metadata:
      labels:
        app: trial
    spec:
      containers:
      - name: trial
        # We advise you to build, push and use your own image, instead of using instructor's image.
        image: daoducnha29493/trial:v2
        env:
          - name: JAEGER_HOST
            value: simplest-query.observability.svc.cluster.local
        ports:
        - name: trailport
          containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: trial
spec:
  selector:
    app: trial
  ports:
    - port: 8082
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trial
  namespace: monitoring
  labels:
    app: trial
    release: prometheus
spec:
  selector:
    matchLabels:
      app: trial
  endpoints:
  - port: trial
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default